### ISSUE TITLE
Query parse error

### ISSUE THREAD

**Issue by avinash-phaniraj-readify** [ErikEJ/EntityFramework.SqlServerCompact#540]
Hello, 

I ran into this error with CE 3.5. The same test works all right with sql provider. 
I'm not a 100% certain if this is a problem with the provider. 

The pattern that causes this is when a sub-query like approach is used from two different queryables. 
eg 
``
 var devices = theDataContext.Set<EmployeeDevice>();
            var employees = theDataContext.Set<Employee>();
            var result = from employee in employees
                         select new
                         {
                             employee.Id,
                             employee.Name,
                             HasDevices = (devices.FirstOrDefault(a => a.EmployeeId == employee.Id) != null),
                         };

            var finalResult = result.OrderBy(yy => yy.Name).ToList();
``
I'm using EntityFrameworkCore.SqlServerCompact35 2.1.0.1 with CE 3.5.
.Net framework 4.6.2
VS 2017 professional.
EFCore 2.1.1

Any help/advise will be great. 
Thanks.,
Avinash

[TestCode.zip](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/2153738/TestCode.zip)
Error
System.Data.SqlServerCe.SqlCeException
  HResult=0x80131501
  Message=There was an error parsing the query. [ Token line number = 3,Token line offset = 9,Token in error = SELECT ]
  Source=SQL Server Compact ADO.NET Data Provider
  StackTrace:
   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfModelTest.TestHost.Test() in C:\Sandbox\EFModelTest\EfModelTest\TestDataContext.cs:line 34

**Comment by ErikEJ** [comment]
Yes, the SQL CE engine does not work well with nested SELECTs.

Try to materialize the "result" by adding "ToList()"

**Comment by avinash-phaniraj-readify** [comment]
Many thanks Eric.
I can see that linq2sql generates a case statement with exists and the query works.

Is this special handling in linq2sql and different in ef/efcore? 

Any insight will be much appreciated.
Regards 
Avinash

**Comment by ErikEJ** [comment]
>> Is this special handling in linq2sql and different in ef/efcore?

Yes!

**Comment by ErikEJ** [comment]
Yes, changing the default SQL translation (from the EFCore.Relational base provider) should be handeled in the provider, but I am not smart enough to tell you how! 

Maybe @smitpatel can help?

**Comment by ErikEJ** [comment]
As mentioned, alternative is to force client evaluation iso database engine evaluation using ToList or maybe even "UseClientEvalForUnsupportedSqlConstructs" option.

(see https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Query/ExpressionVisitors/SqlCeTranslatingExpressionVisitor.cs )

**Comment by smitpatel** [comment]
Can someone post the QueryModel, SQL being sent to server & what is not supported on SQL CE?
The former 2 can be found while running the query with Trace level logging enabled.

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide more info for the EF Core team

**Comment by avinash-phaniraj-readify** [comment]
Sorry.. been a little caught up.. Will post the queries+ info soon. 
\a
