### ISSUE TITLE
Changing DbType to NText and Image

### ISSUE THREAD

**Issue by malikhassan85** [ErikEJ/EntityFramework.SqlServerCompact#550]
If you have a string property in your entity that has length limitation using ```StringLength()``` attribute, and you tried to run a query over this entity with a where condition on the value for this property, you will get the following exception if the value exceeds StringLength MaximumLength property value:

```
Message: The ntext and image data types cannot be used in WHERE, HAVING, GROUP BY, ON, or IN clauses, except when these data types are used with the LIKE or IS NULL predicates.

Stack trace:

  at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

```
After some investigation, I found that the reason for that is the following logic in ```ConfigureParameter``` function in ```SqlCeStringTypeMapping``` class:

```
             if ((length == null) || (length.Value <= _maxSpecificSize))
             {
                parameter.DbType = System.Data.DbType.String;
                return;
              }
              ((SqlCeParameter)parameter).SqlDbType = SqlDbType.NText;

```

I understand that the reason for changing the DBType for the parameter was to avoid a truncation exception, however, I think changing the DbType should occur only if the parameter value exceeds the maximum size for this DbType (which is 4000 in this case), not when it exceeds the StringLength MaximumLength property value.

To confirm my assumption, I've changed the code to this:

```
            if ((length == null) || (length.Value <= UnicodeMax))
            {
                parameter.DbType = System.Data.DbType.String;
                return;
            }
            ((SqlCeParameter)parameter).SqlDbType = SqlDbType.NText;
```

This code works, no exception will be thrown.

If you're OK with this change, I will be happy to create a PR for it.

### Steps to Produce:

Please checkout this sample code:

https://github.com/avinash-phaniraj-readify/EFCoreTestBed/tree/NtextAndImageDbTypeIssue

```
       static void Main(string[] args)
        {
            var name = "My Name Is Unique";

            var nameIsUnique = CheckIfNameIsUnique(name);

            Console.WriteLine($"Is Name Unique:{nameIsUnique}");

            Console.ReadLine();
        }

        private static bool CheckIfNameIsUnique(string name)
        {
            var ceConnectionString = "Data Source=TestDb.sdf; Persist Security Info = False; ";
            var ceConnection = new SqlCeConnection(ceConnectionString);
            
            ceConnection.Open();

            var options = new DbContextOptionsBuilder<TestDataContext>()
                .UseSqlCe(ceConnection)
                .Options;

            var context = new TestDataContext(options);
            var employees = context.Set<Employee>();

            var employeesList = employees.Where(p => p.Name == name).ToList();

            return employeesList.Count == 0;
        }
```

**Comment by ErikEJ** [comment]
Looks like a good fix, please create a PR - I prefer to get this into the 2.1.0 release before your other PR (that depends on 2.1.2)
