### ISSUE TITLE
Investigate why QueryNavigationsWithForcedClientEvalSqlCeTest all fails now?

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework.SqlServerCompact#556]
Maybe need more help from @smitpatel

**Comment by smitpatel** [comment]
Can I get stack trace and exception message?

**Comment by ErikEJ** [comment]
Hi @smitpatel - sorry for lack of context - you helped me create this to enable the user to force client eval for some of the unsupported nested SELECT constructs, that SQL CE cannot handle: 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Query/ExpressionVisitors/SqlCeTranslatingExpressionVisitor.cs#L22 

With 2.1 (??) this has stopped working, so the shortcutting no longer kicks in.

Tests: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/Query/QueryNavigationsWithForcedClientEvalSqlCeTest.cs

```
Test 'Microsoft.EntityFrameworkCore.Query.QueryNavigationsWithForcedClientEvalSqlCeTest.Collection_select_nav_prop_first_or_default_then_nav_prop_nested_with_orderby(isAsync: True)' failed:
	System.Data.SqlServerCe.SqlCeException : There was an error parsing the query. [ Token line number = 2,Token line offset = 5,Token in error = SELECT ]
	at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
	at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
	at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
	at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
	at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__12`2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

**Comment by smitpatel** [comment]
Most likely some Convert node or some thing wrapping around the SelectExpression. I will debug into it and see what shows up

**Comment by ErikEJ** [comment]
Thanks for your support, @smitpatel

**Comment by smitpatel** [comment]
Apparently `_sqlCeOptions.ClientEvalForUnsupportedSqlConstructs` is false. So we never force eval on client hence test is failing.

**Comment by ErikEJ** [comment]
OMG! https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/f5ac8bbfe96016456e53b722b4af4ce693817539#diff-01f31374cc8e4575c7da63aa04c66dd3 😊
