### ISSUE TITLE
System.TypeLoadException: Method 'Create' in type 'EFCore.SqlCe.Scaffolding.Internal.SqlCeDatabaseModelFactory' from assembly 'EntityFrameworkCore.SqlServerCompact35, Version=2.2.0.0, Culture=neutral, PublicKeyToken=9af395b34ac99006' does not have an implementation.

### ISSUE THREAD

**Issue by Laptop765** [ErikEJ/EntityFramework.SqlServerCompact#578]
Thanks for creating this package!  I haven't used EF before but I've been really needing a new way of managing my existing SqlCe 3.5 SP2 database and am giving this a shot.  I'm hitting an error that I'm wondering if you have any insight for.

Here is the command I tried running from the ClassLibraryProject.Name project folder:
```shell
Scaffold-DbContext -Connection "Data Source=C:\Path\To\db.sdf;password=somepassword;Persist Security Info=True;Encryption Mode=Engine Default;Max Database Size=4000;File Mode=Read Write" -Provider EntityFrameworkCore.SqlServerCompact35 -OutputDir FolderUnderStartupProject\Subfolder -StartupProject ClassLibraryProject.Name
```
It required me to set `ClassLibraryProject.Name` as the `Default project` dropdown in the `Package Manager Console` even though I'm passing in `-StartupProject`.  To be safe I also set the project as the `Startup project` in Visual Studio.

With all of that, I get the below error:
```shell
Build started...
Build succeeded.
System.TypeLoadException: Method 'Create' in type 'EFCore.SqlCe.Scaffolding.Internal.SqlCeDatabaseModelFactory' from assembly 'EntityFrameworkCore.SqlServerCompact35, Version=2.2.0.0, Culture=neutral, PublicKeyToken=9af395b34ac99006' does not have an implementation.
   at EFCore.SqlCe.Design.Internal.SqlCeDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices(String provider, IServiceCollection services, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

Simplified project structure (the relevant portions):
`MainUI`
`Core`

`MainUI` depends on `Core`.  I added the `Microsoft.EntityFrameworkCore`, `Microsoft.EntityFrameworkCore.Design`, `Microsoft.EntityFrameworkCore.Tools`, and `EntityFrameworkCore.SqlServerCompact35` packages to the `Core` project only originally but get the same error after adding them to both projects.

Thanks in advance!

**Comment by ErikEJ** [comment]
Why not simply use my EF Core Power Tools for Reverse Engineering instead?

**Comment by Laptop765** [comment]
Ah I hadn't come across those, I was using [this guide](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/wiki/Using-EF-Core-with-SQL-Server-Compact-in-Traditional-.NET-Applications) which doesn't have a mention of them.

I'll close this and give the `EF Core Power Tools` a shot and re-open if needed.  Thanks for the quick reply!
